import { create } from 'zustand'
import { persist } from 'zustand/middleware'

export type Language = 'zh' | 'en'

interface LanguageState {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

// 翻译字典
const translations = {
  zh: {
    // 通用
    'common.loading': '加载中...',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.create': '创建',
    'common.success': '成功',
    'common.error': '错误',
    'common.confirm': '确认',
    'common.yes': '是',
    'common.no': '否',
    
    // 导航
    'nav.workbench': '工作台',
    'nav.dashboard': '仪表盘',
    'nav.instances': '实例管理',
    'nav.operations': '运维中心',
    'nav.config': '配置管理',
    'nav.skills': '技能管理',
    'nav.feedback': '意见管理',
    'nav.notifications': '通知中心',
    'nav.skillCenter': '技能中心',
    'nav.skillStore': 'Skill 商店',
    'nav.skillsSubmit': '提交 Skill',
    'nav.skillReview': 'Skill 审核',
    'nav.myNotifications': '我的通知',
    'nav.departments': '部门管理',
    'nav.users': '用户管理',
    'nav.token': 'Token 分析',
    'nav.audit': '审计日志',
    'nav.settings': '系统设置',
    'nav.setup': '部署向导',
    'nav.security': '安全与设置',
    'nav.myUsage': '我的使用',
    
    // 登录
    'login.title': 'OpenCLAW Manager',
    'login.subtitle': '企业版 v4.0',
    'login.formTitle': '用户登录',
    'login.username': '用户名',
    'login.password': '密码',
    'login.button': '登录',
    'login.loading': '登录中...',
    'login.usernamePlaceholder': '请输入用户名',
    'login.passwordPlaceholder': '请输入密码',
    'login.initialAccount': '📝 初始管理员账号',
    'login.firstLoginHint': '⚠️ 首次登录后请立即修改密码',
    'login.remember': '记住我',
    'login.forgotPassword': '忘记密码？',
    'login.footer': 'MIT License • 完全免费开源',
    
    // 实例管理
    'instances.title': '实例管理',
    'instances.create': '新建实例',
    'instances.name': '实例名称',
    'instances.endpoint': 'API 端点',
    'instances.apiKey': 'API Key',
    'instances.department': '所属部门',
    'instances.config': '关联配置',
    'instances.skills': '安装 Skills',
    'instances.status': '状态',
    'instances.version': '版本',
    'instances.operations': '操作',
    'instances.batchRestart': '批量重启',
    'instances.noDepartment': '未绑定',
    'instances.selectDepartment': '选择部门',
    'instances.noConfig': '不关联配置',
    'instances.selectConfig': '选择配置',
    'instances.noSkills': '暂无已安装的 Skills',
    
    // 部门管理
    'departments.title': '部门管理',
    'departments.create': '创建部门',
    'departments.name': '部门名称',
    'departments.description': '描述',
    'departments.createdAt': '创建时间',
    'departments.default': '默认部门',
    'departments.deleteConfirm': '确定要删除部门 "{name}" 吗？',
    
    // 配置管理
    'config.title': '配置管理',
    'config.create': '新建配置',
    'config.name': '配置名称',
    'config.description': '描述',
    'config.content': '配置内容（JSON）',
    'config.versionRange': 'OpenCLAW 版本范围',
    'config.updatedAt': '更新时间',
    
    // Skills 管理
    'skills.title': 'Skills 管理',
    'skills.store': '📦 Skill 商店',
    'skills.installed': '✅ 已安装 Skills',
    'skills.install': '安装',
    'skills.installing': '安装中...',
    'skills.uninstall': '卸载',
    'skills.enable': '启用',
    'skills.disable': '禁用',
    'skills.enabled': '已启用',
    'skills.disabled': '已禁用',
    'skills.hint': '💡 已展示 OpenCLAW 官方 Skills。更多社区 Skills 请访问 ClawHub.com，或使用命令行安装：openclaw skill install <skill-id>',
    'skills.allInstalled': '所有官方 Skills 已安装',
    'skills.noDescription': '暂无描述',
    'skills.market.title': 'Skill 商店',
    'skills.market.loading': '加载商店列表...',
    'skills.market.instructions': '从官方仓库安装 Skill。安装后可在"已安装 Skills"中查看和管理。',
    'skills.market.browse': '前往 Skill 商店',
    'skills.market.noSkills': '暂无可用的 Skills',
    'skills.market details': '详情',
    'skills.market installed': '已安装',
    'skills.market installing': '安装中...',
    
    // Skill 提交
    'skills.submit.title': '提交Skill',
    'skills.submit.name': 'Skill名称',
    'skills.submit.description': '描述',
    'skills.submit.category': '分类',
    'skills.submit.tags': '标签(用逗号分隔)',
    'skills.submit.submitting': '提交中...',
    'skills.submit.success': '提交成功!',
    'skills.submit.submit': '提交',
    'skills.submit.cancel': '取消',
    
    // Skill 商店
    'skills.store.title': 'Skill商店',
    'skills.store.search': '搜索Skill...',
    'skills.store.categories': '全部分类',
    'skills.store.total': '总Store数',
    'skills.store.published': '已发布',
    'skills.store.categoriesCount': '分类数',
    'skills.store.invoke': '调用',
    'skills.store.noSkills': '暂无符合条件的Skill',
    'skills.store.submitModal.title': '提交Skill',
    'skills.store.submitModal.desc': '提交新Skill到商店需要经过审核流程。提交后您的Skill将显示在商店中供他人使用。',
    'skills.store.submitModal.go': '去提交',
    
    // Skill 审核
    'skills.review.title': 'Skill审核',
    'skills.review.pending': '待审核',
    'skills.review.reviewsToday': '今日审核',
    'skills.review.approvalRate': '审核通过率',
    'skills.review.comments': '审核意见(可选)',
    'skills.review.approve': '批准',
    'skills.review.reject': '拒绝',
    'skills.review.noPending': '暂无待审核的Skill',
    'skills.review.riskLow': '低风险',
    'skills.review.riskMedium': '中风险',
    'skills.review.riskHigh': '高风险',
    
    // Skill 统计
    'skills.stats.title': 'Skill统计',
    'skills.stats.totalCalls': '总调用次数',
    'skills.stats.totalTokens': '总Tokens消耗',
    'skills.stats.activeSkills': '活跃Skills',
    'skills.stats.timeRange': '统计范围',
    'skills.stats.leaderboard': '调用排行榜',
    'skills.stats.noData': '暂无调用数据',
    'skills.stats.rank': '排名',
    'skills.stats.skillName': 'Skill名称',
    'skills.stats.callCount': '调用次数',
    'skills.stats.tokenTotal': '总Tokens',
    'skills.stats.calls': '次',
    'skills.stats.tokens': 'tokens',
    
    // Token 分析
    'token.title': 'Token 分析',
    'token.totalCost': '💰 总成本',
    'token.totalTokens': '🔢 Token 总量',
    'token.totalRequests': '📊 请求次数',
    'token.dailyTrend': '📈 每日趋势',
    'token.byDepartment': '🏢 部门成本统计',
    'token.department': '部门',
    'token.instanceCount': '实例数',
    'token.requestCount': '请求数',
    'token.tokenTotal': 'Token 总量',
    'token.costTotal': '总成本',
    'token.percentage': '占比',
    'token.viewByTime': '按时间',
    'token.viewByDepartment': '按部门',
    
    // 审计日志
    'audit.title': '审计日志',
    'audit.timestamp': '时间',
    'audit.user': '用户',
    'audit.resource': '资源',
    'audit.operation': '操作',
    'audit.result': '结果',
    'audit.riskLevel': '风险等级',
    
    // 部署向导
    'setup.title': '部署向导',
    'setup.subtitle': '选择部署方式并检测环境，一键完成 OpenCLAW 安装',
    'setup.step1': '选择部署方式',
    'setup.step2': '环境检测',
    'setup.step3': '一键部署',
    'setup.checkEnv': '开始检测环境',
    'setup.checking': '检测中...',
    'setup.deploy': '一键部署',
    'setup.deploying': '部署中...',
    'setup.back': '返回重选',
    'setup.completed': '✅ 环境检测完成',
    'setup.required': '必需项',
    'setup.requiredHint': '* 标记的项目为必需项，所有必需项通过后才能部署',
    'setup.passed': '已通过',
    'setup.fix': '一键修复',
    'setup.fixing': '修复中...',
    
    // 部署方式
    'deploy.windows': '本地直接安装',
    'deploy.windows.desc': '在 Windows 系统中直接安装 OpenCLAW，最简单快捷',
    'deploy.wsl2': 'WSL2 部署',
    'deploy.wsl2.desc': '通过 Windows Subsystem for Linux 2 运行，接近 Linux 生产环境',
    'deploy.docker': 'Docker 部署',
    'deploy.docker.desc': '使用 Docker 容器运行，环境隔离最好，便于迁移',
    'deploy.recommended': '推荐',
    'deploy.howToChoose': '💡 如何选择？',
    'deploy.choose.windows': '第一次使用 或 只想简单快捷 → 选择「本地直接安装」',
    'deploy.choose.wsl2': '有 Linux 经验 或计划后续部署到服务器 → 选择「WSL2 部署」',
    'deploy.choose.docker': '有 Docker 经验 或需要环境隔离 → 选择「Docker 部署」',
    'deploy.pros': '优点',
    'deploy.cons': '缺点',
    'deploy.suitableFor': '适合',
    'deploy.notSuitableFor': '不适合',
    'deploy.confirm': '确认选择，继续下一步',
    'deploy.selected': '已选择',
    
    // 用户管理
    'users.title': '用户管理',
    'users.create': '新建用户',
    'users.username': '用户名',
    'users.password': '密码',
    'users.role': '角色',
    'users.createdAt': '创建时间',
    'users.lastLogin': '最后登录',
    'users.operations': '操作',
    'users.cannotDeleteSelf': '不能删除自己',
    
    // 角色
    'role.admin': '👑 超级管理员',
    'role.operator': '🔧 运维管理员',
    'role.deptAdmin': '📋 部门管理员',
    'role.employee': '👤 普通员工',
    'role.auditor': '📊 审计员',
    
    // 设置
    'settings.title': '系统设置',
    'settings.language': '语言',
    'settings.language.zh': '简体中文',
    'settings.language.en': 'English',
    'settings.theme': '主题',
    'settings.theme.light': '浅色',
    'settings.theme.dark': '深色',
    'settings.theme.auto': '自动',
    
    // 权限不足
    'error.permissionDenied': '🔒 权限不足',
    'error.permissionMessage': '只有超级管理员可以访问用户管理页面',
    'error.back': '返回上一页',
    
    // 提示
    'hint.noData': '暂无数据',
    'hint.noItems': '暂无项目，点击右上角创建',
    
    // 部署相關
    'deployment.title': '部署 OpenCLAW',
    'deployment.subtitle': '指导您完成 OpenCLAW 的环境检查与部署流程',
    'deployment.step1': '选择模式',
    'deployment.step2': '环境检查',
    'deployment.step3': '修复缺失',
    'deployment.step4': '执行部署',
    'deployment.check Now': '开始检查',
    'deployment.checking': '正在检查环境...',
    'deployment.checkPending': '请点击「开始检查」按钮，系统将检测当前环境是否满足部署要求。',
    'deployment.ready': '环境就绪',
    'deployment.readyDesc': '所有必需组件已安装，可以开始部署。',
    'deployment.missing': '环境不满足要求',
    'deployment.missingDesc': '以下必需组件未安装，请先修复：',
    'deployment.error': '检查失败',
    'deployment.errorDesc': '环境检查过程中出现错误，请重试。',
    'deployment.fixing': '环境修复中',
    'deployment.fixingDesc': '正在安装缺失的组件，请耐心等待...',
    'deployment.deployNow': '开始部署',
    'deployment.deploying': '部署进行中...',
    'deployment.restart': '重启服务',
    'deployment.back': '返回',
    'deployment.selectMode': '选择部署模式',
    'deployment.modeDescription': '请选择您希望的部署方式',
    'deployment.mode.windows': 'Windows 原生',
    'deployment.mode.wsl2': 'WSL2',
    'deployment.mode.docker': 'Docker',
    'deployment.installPath': '安装路径',
    'deployment.webPort': 'Web 界面端口',
    'deployment.webhookPort': 'Webhook 端口',
    'deployment.configSaved': '配置保存成功',
    'deployment.includeVerified': '包含已验证的',
    'deployment.role.employee': '普通员工',
    'deployment.role.deptAdmin': '部门管理员',
    'deployment.role.operator': '运维管理员',
    'deployment.role.auditor': '审计员',
    'deployment.role.admin': '超级管理员',
    'deployment.loading': '加载中...',
    'deployment.noRecords': '暂无使用记录',
    'deployment.quota': '配额',
    'deployment.quotaUsed': '已使用',
    'deployment.requestCount': '次请求',
    'deployment.hardening': '一键加固',
    'deployment.securityCheck': '安全检查',
    'deployment.guarding': '执行一键加固',
    'deployment.guardingSuccess': '✅ 安全加固完成！',
    'deployment.guardingFailed': '❌ 加固失败：',
    'deployment.guardConfirm': '确定要执行一键加固吗？',
    'deployment.guard.port': '关闭不必要端口',
    'deployment.guard.portDesc': '减少攻击面，提高系统安全性',
    'deployment.guard.config': '修改默认配置',
    'deployment.guard.configDesc': '避免使用默认端口和凭证',
    'deployment.guard.admin': '以非管理员用户运行',
    'deployment.guard.adminDesc': '遵循最小权限原则',
    'deployment.noResults': '暂无检测结果，点击"开始检测"进行安全检查',
    'deployment.safe': '安全',
    'deployment.warning': '警告',
    'deployment.danger': '危险',
    'deployment.securityTips': '安全建议',
    'deployment.securityTips1': '定期执行安全检查',
    'deployment.securityTips2': '及时更新系统和依赖',
    'deployment.securityTips3': '使用强密码策略',
    'deployment.securityTips4': '限制不必要的端口开放',
    'deployment.exports.title': '数据导出',
    'deployment.exports.selectType': '选择导出类型',
    'deployment.exports.costReport': '全局成本报表',
    'deployment.exports.deptReport': '部门成本报表',
    'deployment.exports.selectMonth': '选择月份',
    'deployment.exports.dept': '选择部门',
    'deployment.exports.desc': '导出说明',
    'deployment.exports.costDesc': '全局成本报表包含:',
    'deployment.exports.costItems': '所有实例的成本统计',
    'deployment.exports.costItems2': '按模型分类的调用次数',
    'deployment.exports.costItems3': '总支出和各项费用明细',
    'deployment.exports.costItems4': '时间序列数据(每日/每小时)',
    'deployment.exports.deptDesc': '部门成本报表包含:',
    'deployment.exports.deptItems': '指定部门的所有成本',
    'deployment.exports.deptItems2': '部门内各实例的费用明细',
    'deployment.exports.deptItems3': '按模型分类的费用占比',
    'deployment.exports.deptItems4': '成本分析和摘要信息',
    'deployment.exports.exportBtn': '✅ 导出报表',
    'deployment.exports.exporting': '导出中...',
    'deployment.exports.successCost': '✅ 成报告显示导出成功!',
    'deployment.exports.successDept': '✅ 部门成本报表导出成功!',
    'deployment.exports.failed': '❌ 导出失败:',
    'deployment.exports.examples': '导出的CSV格式示例',
    'deployment.exports.field': '字段名',
    'deployment.exports.descField': '说明',
    'deployment.exports.timestamp': '时间戳',
    'deployment.exports.instanceId': '实例ID',
    'deployment.exports.instanceName': '实例名称',
    'deployment.exports.model': '模型名称',
    'deployment.exports.calls': '调用次数',
    'deployment.exports.totalTokens': '总token数量',
    'deployment.exports.totalCost': '总费用(美元)',
    'deployment.exports.backup.title': '备份与恢复',
    'deployment.exports.backupDesc': '管理数据库备份，支持手动备份和恢复操作',
    'deployment.exports.backupNow': '立即备份',
    'deployment.exports.backupPending': '备份中...',
    'deployment.exports.backupSuccess': '✅ 备份成功！',
    'deployment.exports.backupFile': '备份文件：',
    'deployment.exports.restoreConfirm': '⚠️ 警告：恢复数据库将覆盖当前数据！\n\n确定要继续吗？',
    'deployment.exports.restoreSuccess': '✅ 恢复成功！',
    'deployment.exports.restoreFailed': '❌ 恢复失败：',
    'deployment.exports.deleteConfirm': '确定要删除这个备份吗？',
    'deployment.exports.deleteSuccess': '✅ 删除成功！',
    'deployment.exports.deleteFailed': '❌ 删除失败：',
    'deployment.exports.noBackups': '暂无备份记录',
    'deployment.exports.backupList': '备份列表',
    'deployment.exports.size': '大小',
    'deployment.exports.created': '创建时间',
    'deployment.exports.restore': '恢复',
    'deployment.exports.lastBackup': '最近备份',
    'deployment.exports.usage.title': '我的使用',
    'deployment.exports.usageDesc': '查看您个人的 Token 使用情况和配额',
    'deployment.exports.monthlyStats': '本月配额使用情况',
    'deployment.exports.usageRecords': '使用记录',
    'deployment.exports.purpose': '用途',
    'deployment.exports.prompt': 'Prompt',
    'deployment.exports.completion': 'Completion',
    'deployment.exports.total': '总计',
    'deployment.exports.quotaUsedPercent': '已使用',
    'deployment.exports.quotalimit': '配额',
    'deployment.exports.overview': '概览',
    'deployment.exports.lastLogin': '最后登录',
    'deployment.exports.noUsers': '暂无用户',
    'deployment.exports.cannotDeleteSelf': '不能删除自己的账号',
    'deployment.exports.createSuccess': '用户创建成功（模拟）',
    'deployment.exports.deleteSuccessSim': '用户删除成功（模拟）',
    'deployment.exports.createFailed': '创建失败：',
    'deployment.exports.deleteFailedSim': '删除失败：',
    'deployment.exports.roleName': '角色',
    'deployment.exports.createUser': '创建新用户',
    'deployment.exports.department': '部门',
    'deployment.exports.bindDepartment': '绑定部门',
    'deployment.exports.unbindDepartment': '解绑部门',
  },
  en: {
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.create': 'Create',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    
    // Navigation
    'nav.workbench': 'Workbench',
    'nav.dashboard': 'Dashboard',
    'nav.instances': 'Instances',
    'nav.operations': 'Operations',
    'nav.config': 'Configuration',
    'nav.skills': 'Skills',
    'nav.feedback': 'Feedback',
    'nav.notifications': 'Notifications',
    'nav.skillCenter': 'Skill Center',
    'nav.skillStore': 'Skill Store',
    'nav.skillsSubmit': 'Submit Skill',
    'nav.skillReview': 'Skill Review',
    'nav.myNotifications': 'My Notifications',
    'nav.departments': 'Departments',
    'nav.users': 'Users',
    'nav.token': 'Token Analysis',
    'nav.audit': 'Audit Logs',
    'nav.settings': 'Settings',
    'nav.setup': 'Deployment',
    'nav.security': 'Security',
    'nav.myUsage': 'My Usage',
    
    // Login
    'login.title': 'OpenCLAW Manager',
    'login.subtitle': 'Enterprise v4.0',
    'login.formTitle': 'Sign In',
    'login.username': 'Username',
    'login.password': 'Password',
    'login.button': 'Sign In',
    'login.loading': 'Signing in...',
    'login.usernamePlaceholder': 'Enter username',
    'login.passwordPlaceholder': 'Enter password',
    'login.initialAccount': '📝 Initial Admin Account',
    'login.firstLoginHint': '⚠️ Please change your password after first login',
    'login.remember': 'Remember Me',
    'login.forgotPassword': 'Forgot Password?',
    'login.footer': 'MIT License • Free and Open Source',
    
    // Instances
    'instances.title': 'Instance Management',
    'instances.create': 'New Instance',
    'instances.name': 'Instance Name',
    'instances.endpoint': 'API Endpoint',
    'instances.apiKey': 'API Key',
    'instances.department': 'Department',
    'instances.config': 'Configuration',
    'instances.skills': 'Install Skills',
    'instances.status': 'Status',
    'instances.version': 'Version',
    'instances.operations': 'Actions',
    'instances.batchRestart': 'Batch Restart',
    'instances.noDepartment': 'Not Bound',
    'instances.selectDepartment': 'Select Department',
    'instances.noConfig': 'No Configuration',
    'instances.selectConfig': 'Select Configuration',
    'instances.noSkills': 'No Skills Installed',
    
    // Departments
    'departments.title': 'Department Management',
    'departments.create': 'Create Department',
    'departments.name': 'Department Name',
    'departments.description': 'Description',
    'departments.createdAt': 'Created At',
    'departments.default': 'Default',
    'departments.deleteConfirm': 'Are you sure to delete department "{name}"?',
    
    // Configuration
    'config.title': 'Configuration',
    'config.create': 'New Configuration',
    'config.name': 'Name',
    'config.description': 'Description',
    'config.content': 'Configuration (JSON)',
    'config.versionRange': 'OpenCLAW Version Range',
    'config.updatedAt': 'Updated At',
    
    // Skills
    'skills.title': 'Skills Management',
    'skills.store': '📦 Skill Store',
    'skills.installed': '✅ Installed Skills',
    'skills.install': 'Install',
    'skills.installing': 'Installing...',
    'skills.uninstall': 'Uninstall',
    'skills.enable': 'Enable',
    'skills.disable': 'Disable',
    'skills.enabled': 'Enabled',
    'skills.disabled': 'Disabled',
    'skills.hint': '💡 Showing OpenCLAW official Skills. For more community Skills, visit ClawHub.com or use CLI: openclaw skill install <skill-id>',
    'skills.allInstalled': 'All official Skills installed',
    'skills.noDescription': 'No description available',
    'skills.market.title': 'Skill Store',
    'skills.market.loading': 'Loading store listing...',
    'skills.market.instructions': 'Install Skills from the official repository. After installation, you can view and manage them in "Installed Skills".',
    'skills.market.browse': 'Go to Skill Store',
    'skills.market.noSkills': 'No skills available yet',
    'skills.market details': 'Details',
    'skills.market installed': 'Installed',
    'skills.market installing': 'Installing...',
    
    // Skill Submit
    'skills.submit.title': 'Submit Skill',
    'skills.submit.name': 'Skill Name',
    'skills.submit.description': 'Description',
    'skills.submit.category': 'Category',
    'skills.submit.tags': 'Tags (comma separated)',
    'skills.submit.submitting': 'Submitting...',
    'skills.submit.success': 'Submitted Successfully!',
    'skills.submit.submit': 'Submit',
    'skills.submit.cancel': 'Cancel',
    
    // Skill Store
    'skills.store.title': 'Skill Store',
    'skills.store.search': 'Search Skills...',
    'skills.store.categories': 'All Categories',
    'skills.store.total': 'Total Store Skills',
    'skills.store.published': 'Published',
    'skills.store.categoriesCount': 'Categories',
    'skills.store.invoke': 'Invoke',
    'skills.store.noSkills': 'No matching Skills found',
    'skills.store.submitModal.title': 'Submit Skill',
    'skills.store.submitModal.desc': 'Submitting a new Skill to the store requires review. After approval, your Skill will be available for others to use.',
    'skills.store.submitModal.go': 'Submit Now',
    
    // Skill Review
    'skills.review.title': 'Skill Review',
    'skills.review.pending': 'Pending Review',
    'skills.review.reviewsToday': 'Reviews Today',
    'skills.review.approvalRate': 'Approval Rate',
    'skills.review.comments': 'Review Comments (Optional)',
    'skills.review.approve': 'Approve',
    'skills.review.reject': 'Reject',
    'skills.review.noPending': 'No Skills pending review',
    'skills.review.riskLow': 'Low Risk',
    'skills.review.riskMedium': 'Medium Risk',
    'skills.review.riskHigh': 'High Risk',
    
    // Skill Stats
    'skills.stats.title': 'Skill Statistics',
    'skills.stats.totalCalls': 'Total Invocations',
    'skills.stats.totalTokens': 'Total Tokens',
    'skills.stats.activeSkills': 'Active Skills',
    'skills.stats.timeRange': 'Time Range',
    'skills.stats.leaderboard': 'Invocation Leaderboard',
    'skills.stats.noData': 'No invocation data available',
    'skills.stats.rank': 'Rank',
    'skills.stats.skillName': 'Skill Name',
    'skills.stats.callCount': 'Calls',
    'skills.stats.tokenTotal': 'Total Tokens',
    'skills.stats.calls': 'calls',
    'skills.stats.tokens': 'tokens',
    
    // Token Analysis
    'token.title': 'Token Analysis',
    'token.totalCost': '💰 Total Cost',
    'token.totalTokens': '🔢 Total Tokens',
    'token.totalRequests': '📊 Total Requests',
    'token.dailyTrend': '📈 Daily Trend',
    'token.byDepartment': '🏢 Department Costs',
    'token.department': 'Department',
    'token.instanceCount': 'Instances',
    'token.requestCount': 'Requests',
    'token.tokenTotal': 'Total Tokens',
    'token.costTotal': 'Total Cost',
    'token.percentage': 'Percentage',
    'token.viewByTime': 'By Time',
    'token.viewByDepartment': 'By Department',
    
    // Audit Logs
    'audit.title': 'Audit Logs',
    'audit.timestamp': 'Timestamp',
    'audit.user': 'User',
    'audit.resource': 'Resource',
    'audit.operation': 'Operation',
    'audit.result': 'Result',
    'audit.riskLevel': 'Risk Level',
    
    // Deployment
    'setup.title': 'Deployment Wizard',
    'setup.subtitle': 'Select deployment method, check environment, and deploy OpenCLAW with one click',
    'setup.step1': 'Select Method',
    'setup.step2': 'Environment Check',
    'setup.step3': 'Deploy',
    'setup.checkEnv': 'Check Environment',
    'setup.checking': 'Checking...',
    'setup.deploy': 'Deploy Now',
    'setup.deploying': 'Deploying...',
    'setup.back': 'Back',
    'setup.completed': '✅ Environment Check Complete',
    'setup.required': 'Required',
    'setup.requiredHint': '* Required items must pass before deployment',
    'setup.passed': 'Passed',
    'setup.fix': 'Fix',
    'setup.fixing': 'Fixing...',
    
    // Deployment Methods
    'deploy.windows': 'Native Windows',
    'deploy.windows.desc': 'Install OpenCLAW directly on Windows, simplest and fastest',
    'deploy.wsl2': 'WSL2 Deployment',
    'deploy.wsl2.desc': 'Run via Windows Subsystem for Linux 2, close to Linux production',
    'deploy.docker': 'Docker Deployment',
    'deploy.docker.desc': 'Run in Docker container, best isolation, easy migration',
    'deploy.recommended': 'Recommended',
    'deploy.howToChoose': '💡 How to Choose?',
    'deploy.choose.windows': 'First time or want simplicity → Choose "Native Windows"',
    'deploy.choose.wsl2': 'Have Linux experience or plan server deployment → Choose "WSL2"',
    'deploy.choose.docker': 'Have Docker experience or need isolation → Choose "Docker"',
    'deploy.pros': 'Pros',
    'deploy.cons': 'Cons',
    'deploy.suitableFor': 'Suitable For',
    'deploy.notSuitableFor': 'Not Suitable For',
    'deploy.confirm': 'Confirm & Continue',
    'deploy.selected': 'Selected',
    
    // Users
    'users.title': 'User Management',
    'users.create': 'New User',
    'users.username': 'Username',
    'users.password': 'Password',
    'users.role': 'Role',
    'users.createdAt': 'Created At',
    'users.lastLogin': 'Last Login',
    'users.operations': 'Actions',
    'users.cannotDeleteSelf': 'Cannot delete self',
    
    // Roles
    'role.admin': '👑 Admin',
    'role.operator': '🔧 Operator',
    'role.deptAdmin': '📋 Dept Admin',
    'role.employee': '👤 Employee',
    'role.auditor': '📊 Auditor',
    
    // Settings
    'settings.title': 'Settings',
    'settings.language': 'Language',
    'settings.language.zh': '简体中文',
    'settings.language.en': 'English',
    'settings.theme': 'Theme',
    'settings.theme.light': 'Light',
    'settings.theme.dark': 'Dark',
    'settings.theme.auto': 'Auto',
    
    // Permission Error
    'error.permissionDenied': '🔒 Permission Denied',
    'error.permissionMessage': 'Only administrators can access user management',
    'error.back': 'Go Back',
    
    // Hints
    'hint.noData': 'No Data',
    'hint.noItems': 'No items, click create to add',
  },
}

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set, get) => ({
      language: 'zh',
      
      setLanguage: (lang: Language) => {
        set({ language: lang })
      },
      
      t: (key: string) => {
        const { language } = get()
        // @ts-ignore - allow dynamic key access
        const translation = translations[language][key]
        return translation ? translation : key
      },
    }),
    {
      name: 'language-storage',
    }
  )
)
